In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization
import pickle

2025-06-01 15:30:34.243144: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-06-01 15:30:34.274515: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1748772034.296099   43036 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1748772034.301880   43036 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1748772034.326527   43036 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

In [2]:
def load_from_disk(path):

    with open(path, "rb") as f:
        loaded_list = pickle.load(f)

    return loaded_list

In [3]:
vocab=load_from_disk('./Vocabulary/vocab.pkl')

In [4]:
print(len(vocab))
print(vocab[0:10])

400002
['<SOS>', '<EOS>', '!', '!!', '!!!', '!!!!', '!!!!!', '!?', '!?!', '"']


In [6]:
vectorize_layer = TextVectorization(
    standardize=None,
    output_mode='int',
    vocabulary=vocab)

In [7]:
vector_vocab=vectorize_layer.get_vocabulary()
print(len(vector_vocab))
print(vector_vocab[0:10])

400004
['', '[UNK]', '<SOS>', '<EOS>', '!', '!!', '!!!', '!!!!', '!!!!!', '!?']


In [8]:
train_captions=load_from_disk('./Data/train_captions.pkl')

In [9]:
print(len(train_captions))
print(train_captions[0:10])

28320
['A child in a pink dress is climbing up a set of stairs in an entry way .', 'A girl going into a wooden building .', 'A little girl climbing into a wooden playhouse .', 'A little girl climbing the stairs to her playhouse .', 'A little girl in a pink dress going into a wooden cabin .', 'A black dog and a spotted dog are fighting', 'A black dog and a tri-colored dog playing with each other on the road .', 'A black dog and a white dog with brown spots are staring at each other in the street .', 'Two dogs of different breeds looking at each other on the road .', 'Two dogs on pavement moving toward each other .']


In [10]:
import string

def preprocess_text(text):
    # Step 1: Convert all characters to lowercase
    text = text.lower()
    
    # Step 2: Remove punctuation
    # str.maketrans('', '', string.punctuation) creates a translation table
    # str.translate(...) removes all punctuation characters in that table
    text = text.translate(str.maketrans('', '', string.punctuation))

    text="<SOS> "+text+" <EOS>"
    
    return text

In [11]:
processed_train_captions=[]
for sentence in train_captions:
    sen=preprocess_text(sentence)
    processed_train_captions.append(sen)

In [12]:
print(len(processed_train_captions))
print(processed_train_captions[0:10])

28320
['<SOS> a child in a pink dress is climbing up a set of stairs in an entry way  <EOS>', '<SOS> a girl going into a wooden building  <EOS>', '<SOS> a little girl climbing into a wooden playhouse  <EOS>', '<SOS> a little girl climbing the stairs to her playhouse  <EOS>', '<SOS> a little girl in a pink dress going into a wooden cabin  <EOS>', '<SOS> a black dog and a spotted dog are fighting <EOS>', '<SOS> a black dog and a tricolored dog playing with each other on the road  <EOS>', '<SOS> a black dog and a white dog with brown spots are staring at each other in the street  <EOS>', '<SOS> two dogs of different breeds looking at each other on the road  <EOS>', '<SOS> two dogs on pavement moving toward each other  <EOS>']


In [14]:
processed_captions=vectorize_layer(processed_train_captions)

In [21]:
print(type(processed_captions))

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [16]:
processed_captions.shape

TensorShape([28320, 38])

In [17]:
processed_captions[0:5,:]

<tf.Tensor: shape=(5, 38), dtype=int64, numpy=
array([[     2,  43013,  98973, 188484,  43013, 285071, 129288, 192976,
        102812, 373320,  43013, 325902, 268049, 341258, 188484,  54276,
        138044, 384125,      3,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0],
       [     2,  43013, 161847, 163748, 191814,  43013, 389565,  86374,
             3,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0],
       [     2,  43013, 223833, 161847, 102812, 191814,  43013, 389565,
        286442,      3,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,

In [19]:
processed_captions_np=processed_captions.numpy()

In [22]:
type(processed_captions_np)

numpy.ndarray

In [24]:
processed_captions_np.shape

(28320, 38)

In [25]:
processed_captions_np[:5,:]

array([[     2,  43013,  98973, 188484,  43013, 285071, 129288, 192976,
        102812, 373320,  43013, 325902, 268049, 341258, 188484,  54276,
        138044, 384125,      3,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0],
       [     2,  43013, 161847, 163748, 191814,  43013, 389565,  86374,
             3,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0],
       [     2,  43013, 223833, 161847, 102812, 191814,  43013, 389565,
        286442,      3,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0,      0,      0,      0,      0,      0,      0,
             0,      0

In [ ]:
np.save('./Data/processed_train_captions.npy',processed_captions_np)